"""esquema inicial

Revision ID: d4d3f7b4b7c1
Revises: 
Create Date: 2026-08-03 16:24:29.084290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d3f7b4b7c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodegas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('capacidad', sa.Float(), nullable=True),
    sa.Column('encargado', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_bodegas_id'), 'bodegas', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_codigo'), 'clientes', ['codigo'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_codigo'), 'proveedores', ['codigo'], unique=True)
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_sku', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('precio_referencia', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('metodo_valorizacion', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('maneja_lotes', sa.Boolean(), nullable=False),
    sa.Column('tipo_producto', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_codigo_sku'), 'skus', ['codigo_sku'], unique=True)
    op.create_index(op.f('ix_skus_id'), 'skus', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('SUPERADMIN', 'ADMIN', 'OPERADOR', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('cotizaciones_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_compra_id'), 'cotizaciones_compra', ['id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_compra_numero'), 'cotizaciones_compra', ['numero'], unique=True)
    op.create_table('cotizaciones_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_venta_id'), 'cotizaciones_venta', ['id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_venta_numero'), 'cotizaciones_venta', ['numero'], unique=True)
    op.create_table('inventarios_fisicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', 'AJUSTADO', name='estadoconteo'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventarios_fisicos_id'), 'inventarios_fisicos', ['id'], unique=False)
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('numero_lote', sa.String(length=100), nullable=False),
    sa.Column('fecha_fabricacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'numero_lote')
    )
    op.create_index(op.f('ix_lotes_id'), 'lotes', ['id'], unique=False)
    op.create_table('ordenes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_oc', sa.String(length=50), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'COMPLETA', 'CANCELADA', name='estadoorden'), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_compra_id'), 'ordenes_compra', ['id'], unique=False)
    op.create_index(op.f('ix_ordenes_compra_numero_oc'), 'ordenes_compra', ['numero_oc'], unique=True)
    op.create_table('precios_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('ultima_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_id', 'sku_id')
    )
    op.create_index(op.f('ix_precios_proveedor_id'), 'precios_proveedor', ['id'], unique=False)
    op.create_table('solicitudes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_compra_id'), 'solicitudes_compra', ['id'], unique=False)
    op.create_index(op.f('ix_solicitudes_compra_numero'), 'solicitudes_compra', ['numero'], unique=True)
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bodega_id', 'codigo')
    )
    op.create_index(op.f('ix_ubicaciones_id'), 'ubicaciones', ['id'], unique=False)
    op.create_table('devoluciones_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devoluciones_compra_id'), 'devoluciones_compra', ['id'], unique=False)
    op.create_table('items_cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_cotizacion_id'), 'items_cotizacion', ['id'], unique=False)
    op.create_table('items_cotizacion_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones_venta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_cotizacion_venta_id'), 'items_cotizacion_venta', ['id'], unique=False)
    op.create_table('items_inventario_fisico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_esperada', sa.Float(), nullable=False),
    sa.Column('cantidad_contada', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventarios_fisicos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_inventario_fisico_id'), 'items_inventario_fisico', ['id'], unique=False)
    op.create_table('items_orden_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_solicitada', sa.Float(), nullable=False),
    sa.Column('cantidad_recibida', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_orden_compra_id'), 'items_orden_compra', ['id'], unique=False)
    op.create_table('items_solicitud_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_compra.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_solicitud_compra_id'), 'items_solicitud_compra', ['id'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SALIDA', name='tipomovimiento'), nullable=False),
    sa.Column('motivo', sa.Enum('COMPRA', 'DEVOLUCION_PROVEEDOR', 'VENTA', 'DEVOLUCION_CLIENTE', 'TRANSFERENCIA_SALIDA', 'TRANSFERENCIA_ENTRADA', 'CONSUMO_INTERNO', 'MERMA', 'AJUSTE', 'STOCK_INICIAL', name='motivomovimiento'), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('referencia', sa.String(length=255), nullable=True),
    sa.Column('documento_origen', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_inventario_id'), 'movimientos_inventario', ['id'], unique=False)
    op.create_table('pedidos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'DESPACHADO', 'FACTURADO', 'CANCELADO', name='estadopedido'), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('impuesto_total', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones_venta.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_venta_id'), 'pedidos_venta', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_venta_numero'), 'pedidos_venta', ['numero'], unique=True)
    op.create_table('propuestas_cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('adjudicada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propuestas_cotizacion_id'), 'propuestas_cotizacion', ['id'], unique=False)
    op.create_table('recepciones_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_compra.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recepciones_compra_id'), 'recepciones_compra', ['id'], unique=False)
    op.create_table('reservas_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('referencia', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_stock_id'), 'reservas_stock', ['id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('cantidad_minima', sa.Float(), nullable=True),
    sa.Column('cantidad_maxima', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_table('despachos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venta.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despachos_venta_id'), 'despachos_venta', ['id'], unique=False)
    op.create_table('devoluciones_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venta.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devoluciones_venta_id'), 'devoluciones_venta', ['id'], unique=False)
    op.create_table('facturas_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('impuesto_porcentaje', sa.Float(), nullable=False),
    sa.Column('impuesto_total', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venta.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_venta_id'), 'facturas_venta', ['id'], unique=False)
    op.create_index(op.f('ix_facturas_venta_numero'), 'facturas_venta', ['numero'], unique=True)
    op.create_table('items_devolucion_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=False),
    sa.Column('item_orden_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_devuelta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devoluciones_compra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_orden_id'], ['items_orden_compra.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_devolucion_compra_id'), 'items_devolucion_compra', ['id'], unique=False)
    op.create_table('items_pedido_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Float(), nullable=False),
    sa.Column('cantidad_despachada', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_venta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_pedido_venta_id'), 'items_pedido_venta', ['id'], unique=False)
    op.create_table('items_propuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propuesta_id', sa.Integer(), nullable=False),
    sa.Column('item_cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_cotizacion_id'], ['items_cotizacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['propuesta_id'], ['propuestas_cotizacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_propuesta_id'), 'items_propuesta', ['id'], unique=False)
    op.create_table('items_recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('item_orden_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_recibida', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_orden_id'], ['items_orden_compra.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recepcion_id'], ['recepciones_compra.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_recepcion_id'), 'items_recepcion', ['id'], unique=False)
    op.create_table('items_despacho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('despacho_id', sa.Integer(), nullable=False),
    sa.Column('item_pedido_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_despachada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['despacho_id'], ['despachos_venta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['items_pedido_venta.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_despacho_id'), 'items_despacho', ['id'], unique=False)
    op.create_table('items_devolucion_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=False),
    sa.Column('item_pedido_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_devuelta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devoluciones_venta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_pedido_id'], ['items_pedido_venta.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_devolucion_venta_id'), 'items_devolucion_venta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_devolucion_venta_id'), table_name='items_devolucion_venta')
    op.drop_table('items_devolucion_venta')
    op.drop_index(op.f('ix_items_despacho_id'), table_name='items_despacho')
    op.drop_table('items_despacho')
    op.drop_index(op.f('ix_items_recepcion_id'), table_name='items_recepcion')
    op.drop_table('items_recepcion')
    op.drop_index(op.f('ix_items_propuesta_id'), table_name='items_propuesta')
    op.drop_table('items_propuesta')
    op.drop_index(op.f('ix_items_pedido_venta_id'), table_name='items_pedido_venta')
    op.drop_table('items_pedido_venta')
    op.drop_index(op.f('ix_items_devolucion_compra_id'), table_name='items_devolucion_compra')
    op.drop_table('items_devolucion_compra')
    op.drop_index(op.f('ix_facturas_venta_numero'), table_name='facturas_venta')
    op.drop_index(op.f('ix_facturas_venta_id'), table_name='facturas_venta')
    op.drop_table('facturas_venta')
    op.drop_index(op.f('ix_devoluciones_venta_id'), table_name='devoluciones_venta')
    op.drop_table('devoluciones_venta')
    op.drop_index(op.f('ix_despachos_venta_id'), table_name='despachos_venta')
    op.drop_table('despachos_venta')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_reservas_stock_id'), table_name='reservas_stock')
    op.drop_table('reservas_stock')
    op.drop_index(op.f('ix_recepciones_compra_id'), table_name='recepciones_compra')
    op.drop_table('recepciones_compra')
    op.drop_index(op.f('ix_propuestas_cotizacion_id'), table_name='propuestas_cotizacion')
    op.drop_table('propuestas_cotizacion')
    op.drop_index(op.f('ix_pedidos_venta_numero'), table_name='pedidos_venta')
    op.drop_index(op.f('ix_pedidos_venta_id'), table_name='pedidos_venta')
    op.drop_table('pedidos_venta')
    op.drop_index(op.f('ix_movimientos_inventario_id'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_items_solicitud_compra_id'), table_name='items_solicitud_compra')
    op.drop_table('items_solicitud_compra')
    op.drop_index(op.f('ix_items_orden_compra_id'), table_name='items_orden_compra')
    op.drop_table('items_orden_compra')
    op.drop_index(op.f('ix_items_inventario_fisico_id'), table_name='items_inventario_fisico')
    op.drop_table('items_inventario_fisico')
    op.drop_index(op.f('ix_items_cotizacion_venta_id'), table_name='items_cotizacion_venta')
    op.drop_table('items_cotizacion_venta')
    op.drop_index(op.f('ix_items_cotizacion_id'), table_name='items_cotizacion')
    op.drop_table('items_cotizacion')
    op.drop_index(op.f('ix_devoluciones_compra_id'), table_name='devoluciones_compra')
    op.drop_table('devoluciones_compra')
    op.drop_index(op.f('ix_ubicaciones_id'), table_name='ubicaciones')
    op.drop_table('ubicaciones')
    op.drop_index(op.f('ix_solicitudes_compra_numero'), table_name='solicitudes_compra')
    op.drop_index(op.f('ix_solicitudes_compra_id'), table_name='solicitudes_compra')
    op.drop_table('solicitudes_compra')
    op.drop_index(op.f('ix_precios_proveedor_id'), table_name='precios_proveedor')
    op.drop_table('precios_proveedor')
    op.drop_index(op.f('ix_ordenes_compra_numero_oc'), table_name='ordenes_compra')
    op.drop_index(op.f('ix_ordenes_compra_id'), table_name='ordenes_compra')
    op.drop_table('ordenes_compra')
    op.drop_index(op.f('ix_lotes_id'), table_name='lotes')
    op.drop_table('lotes')
    op.drop_index(op.f('ix_inventarios_fisicos_id'), table_name='inventarios_fisicos')
    op.drop_table('inventarios_fisicos')
    op.drop_index(op.f('ix_cotizaciones_venta_numero'), table_name='cotizaciones_venta')
    op.drop_index(op.f('ix_cotizaciones_venta_id'), table_name='cotizaciones_venta')
    op.drop_table('cotizaciones_venta')
    op.drop_index(op.f('ix_cotizaciones_compra_numero'), table_name='cotizaciones_compra')
    op.drop_index(op.f('ix_cotizaciones_compra_id'), table_name='cotizaciones_compra')
    op.drop_table('cotizaciones_compra')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_skus_id'), table_name='skus')
    op.drop_index(op.f('ix_skus_codigo_sku'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_codigo'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_codigo'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_bodegas_id'), table_name='bodegas')
    op.drop_table('bodegas')
    # ### end Alembic commands ###
