"""multi-moneda: moneda y tipo_cambio

Revision ID: db28655363a1
Revises: f887f6af6b0c
Create Date: 2026-08-03 22:00:01.299868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db28655363a1'
down_revision: Union[str, None] = 'f887f6af6b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default para rellenar filas existentes (la BD ya tiene datos).
    # GTQ como moneda base y 1.0 como tipo de cambio por defecto.
    moneda = lambda: sa.Column('moneda', sa.String(length=3), nullable=False, server_default='GTQ')  # noqa: E731
    tipo_cambio = lambda: sa.Column('tipo_cambio', sa.Float(), nullable=False, server_default='1.0')  # noqa: E731

    op.add_column('proveedores', moneda())
    op.add_column('clientes', moneda())
    op.add_column('empresas', sa.Column('tipo_cambio_usd', sa.Float(), nullable=False, server_default='7.80'))
    op.add_column('ordenes_compra', moneda())
    op.add_column('ordenes_compra', tipo_cambio())
    op.add_column('cotizaciones_venta', moneda())
    op.add_column('cotizaciones_venta', tipo_cambio())
    op.add_column('pedidos_venta', moneda())
    op.add_column('pedidos_venta', tipo_cambio())
    op.add_column('facturas_venta', moneda())
    op.add_column('facturas_venta', tipo_cambio())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedores', 'moneda')
    op.drop_column('pedidos_venta', 'tipo_cambio')
    op.drop_column('pedidos_venta', 'moneda')
    op.drop_column('ordenes_compra', 'tipo_cambio')
    op.drop_column('ordenes_compra', 'moneda')
    op.drop_column('facturas_venta', 'tipo_cambio')
    op.drop_column('facturas_venta', 'moneda')
    op.drop_column('empresas', 'tipo_cambio_usd')
    op.drop_column('cotizaciones_venta', 'tipo_cambio')
    op.drop_column('cotizaciones_venta', 'moneda')
    op.drop_column('clientes', 'moneda')
    # ### end Alembic commands ###
